### ISSUE TITLE
move repo to github.com/satzbeleg

### ISSUE THREAD

**Issue by ulf1** [satzbeleg/bwsample#51]
## TODO
- [x] Move repo to https://github.com/satzbeleg
- [x] Change PyPi settings
- [x] Change zenodo settings
