### ISSUE TITLE
Bug suspected

### ISSUE THREAD

**Issue by ulf1** [satzbeleg/bwsample#70]
https://github.com/satzbeleg/bwsample/blob/749938bb11a65eb34ee4b67dc152fd3d3cdc7541/bwsample/ranking.py#L324

It should be
```
Q = 1 - P   # <<< Missing!
Q = Q.multiply(cnt > cnt.T)
```

## TODO
- [ ] fix the bug
- [ ] Update Tech Report with new computations
- [ ] Add unit tests to avoid this error in the future
